### ISSUE TITLE
Fails to install on Windows 10

### ISSUE THREAD

**Issue by aleybovich** [bitcoinjs/bip39#112]
When installing on Windows 10, I get an error:

```
C:\dev\path-protocol\node_modules\eccrypto\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while
trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\dev\path-protocol\node_modules\eccrypto\node_modules\secp256k1
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.4 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.4 rebuild script.
```

**Comment by junderw** [comment]
1. You need to install native module building environment
2. This is an issue with secp256k1 library, which is not a dependency of bip39. So there is nothing we can do. Raise an issue with them.

**Comment by aleybovich** [comment]
Reported in the wrong library
