### ISSUE TITLE
9 word mnemonic being broken by latest patch

### ISSUE THREAD

**Issue by akegalj** [bitcoinjs/bip39#52]
```
[akegalj@notebook npm]$ npm i bip39@v2.2.0 --save
npm WARN saveError ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
/home/akegalj/projects/iohk/npm
└─┬ bip39@2.2.0 
  ├─┬ create-hash@1.1.3 
  │ ├─┬ cipher-base@1.0.3 
  │ │ └── inherits@2.0.3  deduped
  │ ├── inherits@2.0.3 
  │ ├─┬ ripemd160@2.0.1 
  │ │ ├─┬ hash-base@2.0.2 
  │ │ │ └── inherits@2.0.3  deduped
  │ │ └── inherits@2.0.3  deduped
  │ └─┬ sha.js@2.4.8 
  │   └── inherits@2.0.3  deduped
  ├─┬ pbkdf2@3.0.12 
  │ ├── create-hash@1.1.3  deduped
  │ ├─┬ create-hmac@1.1.6 
  │ │ ├── cipher-base@1.0.3  deduped
  │ │ ├── create-hash@1.1.3  deduped
  │ │ ├── inherits@2.0.3  deduped
  │ │ ├── ripemd160@2.0.1  deduped
  │ │ ├── safe-buffer@5.0.1  deduped
  │ │ └── sha.js@2.4.8  deduped
  │ ├── ripemd160@2.0.1  deduped
  │ ├── safe-buffer@5.0.1 
  │ └── sha.js@2.4.8  deduped
  ├── randombytes@2.0.3 
  └── unorm@1.4.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
[akegalj@notebook npm]$ ls
node_modules
[akegalj@notebook npm]$ node
> var bip = require('bip39')
undefined
> bip.generateMnemonic()
'hair skate prison broken park great twin gauge cool jewel pear shy'
> bip.generateMnemonic(96)
'renew milk guide erode accuse opinion soda bus fold'
```
```
[akegalj@notebook npm]$ rm -rf node_modules/
[akegalj@notebook npm]$ npm i bip39@v2.3.0 --save
npm WARN saveError ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
/home/akegalj/projects/iohk/npm
└─┬ bip39@2.3.0 
  ├─┬ create-hash@1.1.3 
  │ ├─┬ cipher-base@1.0.3 
  │ │ └── inherits@2.0.3  deduped
  │ ├── inherits@2.0.3 
  │ ├─┬ ripemd160@2.0.1 
  │ │ ├─┬ hash-base@2.0.2 
  │ │ │ └── inherits@2.0.3  deduped
  │ │ └── inherits@2.0.3  deduped
  │ └─┬ sha.js@2.4.8 
  │   └── inherits@2.0.3  deduped
  ├─┬ pbkdf2@3.0.12 
  │ ├── create-hash@1.1.3  deduped
  │ ├─┬ create-hmac@1.1.6 
  │ │ ├── cipher-base@1.0.3  deduped
  │ │ ├── create-hash@1.1.3  deduped
  │ │ ├── inherits@2.0.3  deduped
  │ │ ├── ripemd160@2.0.1  deduped
  │ │ ├── safe-buffer@5.0.1  deduped
  │ │ └── sha.js@2.4.8  deduped
  │ ├── ripemd160@2.0.1  deduped
  │ ├── safe-buffer@5.0.1 
  │ └── sha.js@2.4.8  deduped
  ├── randombytes@2.0.3 
  └── unorm@1.4.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
[akegalj@notebook npm]$ node
> var bip = require('bip39')
undefined
> bip.generateMnemonic()
'bracket what scene civil soldier master crop peace hub paddle cross comic'
> bip.generateMnemonic(96)
'oven need prosper kitten vessel offer stable wasp ready'

```
```
[akegalj@notebook npm]$ rm -rf node_modules/
[akegalj@notebook npm]$ npm i bip39@v2.3.1 --save
npm WARN saveError ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
/home/akegalj/projects/iohk/npm
└─┬ bip39@2.3.1 
  ├─┬ create-hash@1.1.3 
  │ ├─┬ cipher-base@1.0.3 
  │ │ └── inherits@2.0.3  deduped
  │ ├── inherits@2.0.3 
  │ ├─┬ ripemd160@2.0.1 
  │ │ ├─┬ hash-base@2.0.2 
  │ │ │ └── inherits@2.0.3  deduped
  │ │ └── inherits@2.0.3  deduped
  │ └─┬ sha.js@2.4.8 
  │   └── inherits@2.0.3  deduped
  ├─┬ pbkdf2@3.0.12 
  │ ├── create-hash@1.1.3  deduped
  │ ├─┬ create-hmac@1.1.6 
  │ │ ├── cipher-base@1.0.3  deduped
  │ │ ├── create-hash@1.1.3  deduped
  │ │ ├── inherits@2.0.3  deduped
  │ │ ├── ripemd160@2.0.1  deduped
  │ │ ├── safe-buffer@5.0.1  deduped
  │ │ └── sha.js@2.4.8  deduped
  │ ├── ripemd160@2.0.1  deduped
  │ ├── safe-buffer@5.0.1  deduped
  │ └── sha.js@2.4.8  deduped
  ├── randombytes@2.0.3 
  ├── safe-buffer@5.0.1 
  └── unorm@1.4.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/akegalj/projects/iohk/npm/package.json'
npm WARN npm No description
npm WARN npm No repository field.
npm WARN npm No README data
npm WARN npm No license field.
[akegalj@notebook npm]$ node
> var bip = require('bip39')
undefined
> bip.generateMnemonic()
'churn purse awful tent grid teach super target flash glance indoor warm'
> bip.generateMnemonic(96)
TypeError: Invalid entropy
    at entropyToMnemonic (/home/akegalj/projects/iohk/npm/node_modules/bip39/index.js:94:37)
    at Object.generateMnemonic (/home/akegalj/projects/iohk/npm/node_modules/bip39/index.js:120:10)
    at repl:1:5
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:191:7)
> 

```
Hm, it looks to me its a breaking change. At least it broke our package :)

Don't you think this should be major change bump at least. I would even call this a breaking change and maybe bump to `3.0.0`

**Comment by dcousens** [comment]
9 words are non-standard,  and it was a bug that our implementation was accepting them as valid.

This was fixed in the BIP as a patch,  so we had to follow suite, see  https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic

> The allowed size of ENT is 128-256 bits.

For existing mnemonics,  you can still use `mnemonicToSeed` without issue.

**Comment by akegalj** [comment]
@dcousens thanks for the quick response. Ok, yes. That is a valid point.

We have some custom 9 word mnemonic use case so as a workaround we fallback to the old version. Thanks, closing.
